#!/usr/bin/env bash

start_revision="$@"

if [[ $start_revision -eq "" ]]; then
  start_revision="HEAD"
fi

revisions=$(git rev-list "$start_revision")

for revision in $revisions; do
  git show $revision
  echo -n "Press enter to continue, Ctrl-C to quit ..."
  read
  clear
done